#!/usr/bin/env python3
"""Generate Sources/UllageCore/ModelWindows.swift from models.dev.

Prompt capacity per model, from first-party providers only: models.dev's
`limit.input` when it states one (GPT-5: 272k of a 400k context), else
`limit.context`. Ids are normalised the way WindowLimits.normalize does
(lower-case, `.` -> `-`), and an id two providers disagree on is dropped:
no entry is better than a wrong one. Usage:

    curl -sfL https://models.dev/api.json -o /tmp/models.json
    scripts/model-windows.py /tmp/models.json > Sources/UllageCore/ModelWindows.swift
"""
import datetime, json, sys

FIRST_PARTY = ["openai", "google", "xai", "deepseek", "alibaba", "moonshotai", "zai", "mistral",
               "minimax", "meta", "cohere", "amazon-bedrock-nova"]

def normalize(model_id):
    s = model_id.lower().split("/")[-1].split(":")[0]
    return s.replace(".", "-")

data = json.load(open(sys.argv[1]))
windows, conflicts = {}, set()
for provider in FIRST_PARTY:
    for model_id, model in data.get(provider, {}).get("models", {}).items():
        limit = model.get("limit") or {}
        window = limit.get("input") or limit.get("context")
        if not isinstance(window, int) or window < 1000:
            continue
        key = normalize(model_id)
        if key.startswith("claude"):
            continue  # WindowLimits.table holds Claude, from observed sessions
        if key in windows and windows[key] != window:
            conflicts.add(key)
        windows.setdefault(key, window)
for key in conflicts:
    windows.pop(key, None)

print("// Generated by scripts/model-windows.py from https://models.dev/api.json")
print(f"// on {datetime.date.today().isoformat()}. Do not edit by hand; re-run the script.")
print("")
print("/// Prompt capacity of non-Claude models, matched exactly (or with a dated")
print("/// snapshot suffix), never by prefix: a newer model must not inherit an")
print("/// older one's window. See `WindowLimits.knownLimit(for:)`.")
print("enum ModelWindows {")
print("    static let table: [String: Int] = [")
for key in sorted(windows):
    print(f'        "{key}": {windows[key]},')
print("    ]")
print("}")
